server:
  port: 9901

spring:
  cloud:
    gateway:
      routes:
      - id: bin
        uri: http://httpbin.org:80
        predicates:
          - Path=/get
        filters:
          - AddRequestHeader=Hello,Gateway
