server:
    port: 9902
  
spring:
  cloud:
    gateway:
      routes:
      - id: bin
        uri: http://httpbin.org:80
        predicates:
          - Path=/get
        filters:
          - AddRequestHeader=Hello,Gateway-Q
      - id: risk-analysis-digital-payment
        uri: http://localhost:9900/
        predicates:
          - Path=/risk/analysis
        filters:
          - AddRequestHeader=Hello,Gateway
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,bean"

logging:
  level:
    org.springframework: DEBUG
